// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_get_images from "./routes/api/get_images.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $i from "./routes/i.tsx";
import * as $index from "./routes/index.tsx";
import * as $SearchImageForm from "./islands/SearchImageForm.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/get_images.ts": $api_get_images,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/i.tsx": $i,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/SearchImageForm.tsx": $SearchImageForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
